### ISSUE TITLE
Grannys too sexual while black tall guy around..

### ISSUE THREAD

**Issue by Airesmat** [HIBICUS-CAI/PreWorkRenderEngine#1]

**Comment by HIBICUS-CAI** [comment]
Sorry I don't think I've understood what this issue is meaning.
But this repo hasn't been updated after being merged to [this project](https://github.com/HIBICUS-CAI/HycFrame3D), if there is any problem please try to use hycframe3d as a solving way.
I'm going to close this issue, and if hycframe3d doesn't fix your problem please create a new issue there.
Thanks for your comment.
